apiVersion: v1
kind: Service
metadata:
  name: esewa-sdc-dev-apigateway
  namespace: esewa-sdc-dev
spec:
  type: NodePort
  selector:
    app: esewa-sdc-dev-apigateway
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30180
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: esewa-sdc-dev-apigateway
  namespace: esewa-sdc-dev
spec:
  selector:
    matchLabels:
      app: esewa-sdc-dev-apigateway
  replicas: 1
  template:
    metadata:
      labels:
        app: esewa-sdc-dev-apigateway
    spec:
      containers:
      - name: esewa-sdc-dev-apigateway
        image: 10.44.85.80:8082/esewa-development/apigateway
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "development"
        - name: TZ
          value: "Asia/Kolkata"
      imagePullSecrets:
        - name: jfrog.artifactory
  strategy:
    type: Recreate

