apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: esewa-sdc-dev-apigateway
    namespace: project
spec:
   maxReplicas: 5
   minReplicas: 1
   scaleTargetRef:
         apiVersion: apps/v1
         kind: Deployment
         name: esewa-sdc-dev-apigateway
   targetCPUUtilizationPercentage: 9
