apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  selector:
    matchLabels:
       app: apachedeployment
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: apachedeployment
    spec:
      containers:
      - name: apachedeployment
        image: 192:168:207:133:8081/demo/test
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets: jfrog.cred
